[package]
name = "tp2p"
version = "0.1.0"
authors = ["dgcampbe <dgcampbe@gmail.com>"]

# [lib]
# name = "tp2p"
# crate-type = ["dylib"]

[dependencies]
merkle = "1.11.0"
ring = "0.16.9"
rand = "0.7.2"
time = "0.1.42"
chrono = "0.4.9"
error-chain = "0.12.1"
rayon = "1.2.0"
cpython = "0.3.0"
